#!/bin/sh

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -e

cd "$(dirname "$0")/.."

echo "Running CI build ..."
date "+%H:%M:%S"

# ensure dependencies are installed
script/bootstrap

# run tests
script/test

# run linter
script/lint
