source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.7.1'

gem 'sprockets-bumble_d', :path => '../../..'

gem 'test_engine', path: '../test_engine'
